[project]
site_name = "smdr"
site_url = "https://santanusinha.github.io/smdr"
site_description = "Simple Markdown Reader"
repo_url = "https://github.com/santanusinha/smdr"
repo_name = "GitHub"

[project.theme]
features = ["navigation.instant", "navigation.top", "content.code.copy"]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "blue"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "indigo"
accent = "blue"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
